<a href="https://colab.research.google.com/github/Sayak-coder/HateSpeech-detection/blob/main/hatespeech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import transformers
from transformers import pipeline

In [26]:
df = pd.read_csv('/content/drive/MyDrive/StereoQueerEval/Dataset from IIT Hydrabad/Wiki Madlibs” Eval Dataset/hi-Latn_sentence_templates.csv')
df.head()

        template  toxicity              phrase
0  i_am_identity  nontoxic        ma Purana hu
1  i_am_identity  nontoxic          ma kala hu
2  i_am_identity  nontoxic         ma andha hu
3  i_am_identity  nontoxic        ma purush hu
4  i_am_identity  nontoxic  ma Bahot Purana hu

In [27]:
df['toxicity'].unique()

array(['nontoxic', 'toxic'], dtype=object)

In [28]:
df['template'].unique()

array(['i_am_identity', 'i_hate_identity_people',
       'you_are_a_adjective_identity_person',
       'being_identity_is_adjective'], dtype=object)

In [29]:
df['toxicity'] = df['toxicity'].map({'nontoxic': 0, 'toxic': 1})
df.head()

        template  toxicity              phrase
0  i_am_identity         0        ma Purana hu
1  i_am_identity         0          ma kala hu
2  i_am_identity         0         ma andha hu
3  i_am_identity         0        ma purush hu
4  i_am_identity         0  ma Bahot Purana hu

In [40]:
df['template'].values

array(['i_am_identity', 'i_am_identity', 'i_am_identity', ...,
       'you_are_a_adjective_identity_person',
       'you_are_a_adjective_identity_person',
       'you_are_a_adjective_identity_person'], dtype=object)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500)

In [44]:
from sklearn.model_selection import GroupKFold

X = tv.fit_transform(df['phrase']).toarray()
y=df['toxicity']
groups = df['template'].values

gkf=GroupKFold(n_splits=4)

fold = 1
for train_idx, test_idx in gkf.split(X, y, groups=groups):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

In [45]:
from sklearn.naive_bayes import MultinomialNB
hatespeech_detect_model = MultinomialNB().fit(X_train, y_train)

In [46]:
y_pred=hatespeech_detect_model.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

0.935126582278481

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       591
           1       0.00      0.00      0.00        41

    accuracy                           0.94       632
   macro avg       0.47      0.50      0.48       632
weighted avg       0.87      0.94      0.90       632

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))